[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
corescbsdk = { path = "../corescbsdk" }

tokio = {version = "1", features = ["full"]}
pretty_env_logger = "0.5"
log = "0.4"

